<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\**" />
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Exceptions\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LYBT.Module.Logs\LYBT.Module.Logs.csproj" />
    <ProjectReference Include="..\LYBT.Infrastructure\LYBT.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Repositories\" />
    <Folder Include="Mapping\" />
  </ItemGroup>

</Project>
