<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>LYBT.Desktop.Users.Shared</AssemblyName>
		<RootNamespace>LYBT.Desktop.Users.Shared</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.DryIoc" Version="9.0.537" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\LYBT.Desktop.Core.csproj" />
		<ProjectReference Include="..\..\Services\LYBT.Desktop.Services.csproj" />
		<ProjectReference Include="..\..\Infrastructure\LYBT.Desktop.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\..\src\Shared\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
	</ItemGroup>

</Project>