-- 临时删除已手动添加的字段，准备通过EF迁移重新添加
USE LYBTDB;
GO

-- 检查并删除已存在的字段
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Department')
    ALTER TABLE Users DROP COLUMN Department;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Position')
    ALTER TABLE Users DROP COLUMN Position;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Remark')
    ALTER TABLE Users DROP COLUMN Remark;

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'UpdateTime')
    ALTER TABLE Users DROP COLUMN UpdateTime;

PRINT '已删除手动添加的字段，准备通过EF迁移重新添加';