<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BaseOutputPath>..\BIN</BaseOutputPath>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="obj\**" />
	  <EmbeddedResource Remove="obj\**" />
	  <None Remove="obj\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.17" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.17">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.17" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Shared\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
		<ProjectReference Include="..\..\..\Shared\LYBT.Shared.Utilities\LYBT.Shared.Utilities.csproj" />
		<ProjectReference Include="..\..\Core\LYBT.Infrastructure\LYBT.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Core\LYBT.Models\LYBT.Models.csproj" />
		<ProjectReference Include="..\LYBT.Module.Users\LYBT.Module.Users.csproj" />
	</ItemGroup>
</Project>
