<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BaseOutputPath>..\BIN</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LYBT.Common\LYBT.Common.csproj" />
		<ProjectReference Include="..\LYBT.Infrastructure\LYBT.Infrastructure.csproj" />
	</ItemGroup>

</Project>
