//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LYBT.Desktop.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LYBT.Desktop.Resources.Strings.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凌隐宝堂中医诊所诊疗系统.
        /// </summary>
        internal static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ling Yin Bao Tang TCM Clinic System.
        /// </summary>
        internal static string BrandNameShort {
            get {
                return ResourceManager.GetString("BrandNameShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凌隐宝堂中医诊所.
        /// </summary>
        internal static string ClinicDescription {
            get {
                return ResourceManager.GetString("ClinicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凌隐宝堂.
        /// </summary>
        internal static string ClinicName {
            get {
                return ResourceManager.GetString("ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凌隐宝堂中医诊所.
        /// </summary>
        internal static string ClinicNameFull {
            get {
                return ResourceManager.GetString("ClinicNameFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传承经典 · 数字化诊疗.
        /// </summary>
        internal static string ClinicSlogan {
            get {
                return ResourceManager.GetString("ClinicSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭程序按钮.
        /// </summary>
        internal static string CloseButtonA11y {
            get {
                return ResourceManager.GetString("CloseButtonA11y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭应用程序.
        /// </summary>
        internal static string CloseButtonHelp {
            get {
                return ResourceManager.GetString("CloseButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 凌隐宝堂. All rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在初始化....
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地模式.
        /// </summary>
        internal static string LocalMode {
            get {
                return ResourceManager.GetString("LocalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用本地数据库，数据不与服务器同步.
        /// </summary>
        internal static string LocalModeHelp {
            get {
                return ResourceManager.GetString("LocalModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录按钮.
        /// </summary>
        internal static string LoginButtonA11y {
            get {
                return ResourceManager.GetString("LoginButtonA11y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击登录到管理系统.
        /// </summary>
        internal static string LoginButtonHelp {
            get {
                return ResourceManager.GetString("LoginButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在登录....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无数据.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂无项目.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到结果.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码输入框.
        /// </summary>
        internal static string PasswordInputA11y {
            get {
                return ResourceManager.GetString("PasswordInputA11y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的密码.
        /// </summary>
        internal static string PasswordHelp {
            get {
                return ResourceManager.GetString("PasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在处理....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 远程服务.
        /// </summary>
        internal static string RemoteService {
            get {
                return ResourceManager.GetString("RemoteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接到远程服务器进行数据同步.
        /// </summary>
        internal static string RemoteServiceHelp {
            get {
                return ResourceManager.GetString("RemoteServiceHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住账号.
        /// </summary>
        internal static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勾选后将保存密码.
        /// </summary>
        internal static string RememberPasswordHelp {
            get {
                return ResourceManager.GetString("RememberPasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住账号.
        /// </summary>
        internal static string RememberUsername {
            get {
                return ResourceManager.GetString("RememberUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勾选后将保存用户名.
        /// </summary>
        internal static string RememberUsernameHelp {
            get {
                return ResourceManager.GetString("RememberUsernameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重试按钮.
        /// </summary>
        internal static string RetryButtonA11y {
            get {
                return ResourceManager.GetString("RetryButtonA11y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （已保存）.
        /// </summary>
        internal static string SavedPasswordIndicator {
            get {
                return ResourceManager.GetString("SavedPasswordIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存中....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在切换模式....
        /// </summary>
        internal static string SwitchingMode {
            get {
                return ResourceManager.GetString("SwitchingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍候，系统正在重置连接.
        /// </summary>
        internal static string SwitchingModeDescription {
            get {
                return ResourceManager.GetString("SwitchingModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在同步....
        /// </summary>
        internal static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户登录.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名输入框.
        /// </summary>
        internal static string UsernameInputA11y {
            get {
                return ResourceManager.GetString("UsernameInputA11y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的用户名.
        /// </summary>
        internal static string UsernameHelp {
            get {
                return ResourceManager.GetString("UsernameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.0.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本 1.0.0.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 凌隐宝堂中医诊所诊疗系统.
        /// </summary>
        internal static string SplashScreenTitle {
            get {
                return ResourceManager.GetString("SplashScreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作成功.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
