<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BaseOutputPath>..\..\BIN</BaseOutputPath>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
	</ItemGroup>

</Project>