<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BaseOutputPath>..\..\BIN</BaseOutputPath>
		<LangVersion>12.0</LangVersion>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<WarningsAsErrors />
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyTitle>LYBT Shared Utilities</AssemblyTitle>
		<AssemblyDescription>凌隐宝堂中医诊所系统 - 共享工具类库</AssemblyDescription>
		<AssemblyCompany>凌隐宝堂</AssemblyCompany>
		<AssemblyProduct>LYBT 中医诊所系统</AssemblyProduct>
		<Copyright>Copyright © 凌隐宝堂 2025</Copyright>
		<Version>1.0.0</Version>
		<FileVersion>1.0.0.0</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
  	<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8" />
		<ProjectReference Include="..\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
	</ItemGroup>

</Project>