// <auto-generated />
using System;
using LYBT.Module.FormulaTemplates.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LYBT.Module.FormulaTemplates.Migrations
{
    [DbContext(typeof(FormulaTemplateDbContext))]
    partial class FormulaTemplateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LYBT.Module.FormulaTemplates.Models.FormulaTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_FormulaTemplates_Name");

                    b.ToTable("FormulaTemplates", (string)null);
                });

            modelBuilder.Entity("LYBT.Module.FormulaTemplates.Models.FormulaTemplateModel", b =>
                {
                    b.OwnsMany("LYBT.Module.FormulaTemplates.Models.FormulaTemplateHerbItem", "Herbs", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("FormulaTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("HerbId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("HerbName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(10,3)");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Usage")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("FormulaTemplateId");

                            b1.ToTable("FormulaTemplateHerbs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FormulaTemplateId");
                        });

                    b.Navigation("Herbs");
                });
#pragma warning restore 612, 618
        }
    }
}
