using LYBT.Infrastructure.Constants;
using LYBT.Infrastructure.Web;
using LYBT.Module.Users.Application.Commands;
using LYBT.Module.Users.Application.Queries;
using LYBT.Shared.Models.Contracts.Common;
using LYBT.Shared.Models.Contracts.Users;
using LYBT.Shared.Models.Enums;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Logging;

namespace LYBT.Module.Users.Controllers;

/// <summary>
/// 用户管理 Controller 共享基类
/// 继承 BaseCrudController 提供标准 CRUD，保留用户特化方法
/// </summary>
[ApiController]
[Authorize]
public abstract class BaseUsersController : BaseCrudController<UserListDto, UserDetailDto, UserInputDto, GetUsersQuery>
{
    protected BaseUsersController(ISender sender, ILogger logger)
        : base(sender, logger)
    {
    }

    #region 抽象方法实现

    protected override GetUsersQuery CreateGetListQuery(int page, int pageSize, string? keyword)
    {
        return new GetUsersQuery(page, pageSize, keyword);
    }

    protected override IRequest<Result<UserDetailDto>> CreateCreateCommand(UserInputDto dto, Guid operatorId)
    {
        var (_, _, currentRole) = GetOperator();
        var isAdmin = currentRole == UserRole.SuperAdmin || currentRole == UserRole.Admin;
        return new CreateUserCommand(dto, operatorId, isAdmin);
    }

    protected override IRequest<Result<UserDetailDto>> CreateUpdateCommand(Guid id, UserInputDto dto, Guid operatorId)
    {
        var (_, _, currentRole) = GetOperator();
        var isAdmin = currentRole == UserRole.SuperAdmin || currentRole == UserRole.Admin;
        return new UpdateUserCommand(id, dto, operatorId, isAdmin);
    }

    protected override IRequest<Result> CreateDeleteCommand(Guid id, Guid operatorId)
    {
        var (_, _, currentRole) = GetOperator();
        var isAdmin = currentRole == UserRole.SuperAdmin || currentRole == UserRole.Admin;
        return new DeleteUserCommand(id, operatorId, isAdmin);
    }

    protected override IRequest<Result<UserDetailDto>> CreateToggleStatusCommand(Guid id, Guid operatorId)
    {
        var (_, _, currentRole) = GetOperator();
        var isAdmin = currentRole == UserRole.SuperAdmin || currentRole == UserRole.Admin;
        return new ToggleUserStatusCommand(id, operatorId, isAdmin);
    }

    protected override IRequest<Result<UserDetailDto>> CreateRestoreCommand(Guid id, Guid operatorId)
    {
        return new RestoreUserCommand(id, operatorId);
    }

    protected override IRequest<Result<BatchOperationResultDto>> CreateBatchDeleteCommand(List<Guid> ids, Guid operatorId)
    {
        var (_, _, currentRole) = GetOperator();
        var isAdmin = currentRole == UserRole.SuperAdmin || currentRole == UserRole.Admin;
        return new BatchDeleteUsersCommand(ids, operatorId, isAdmin);
    }

    #endregion

    #region 特化方法

    /// <summary>
    /// 获取当前用户信息
    /// </summary>
    [HttpGet("current")]
    [ProducesResponseType(typeof(ApiResponse<UserDetailDto>), 200)]
    [ProducesResponseType(401)]
    public virtual async Task<IActionResult> GetCurrentUser(CancellationToken cancellationToken = default)
    {
        var userId = BaseClaimsHelper.GetCurrentUserId(User);
        var result = await Sender.Send(new GetCurrentUserQuery(userId), cancellationToken);
        if (!result.IsSuccess) return NotFound(result.Error ?? "用户不存在");
        return Success(result.Value!);
    }

    /// <summary>
    /// 重置用户密码
    /// </summary>
    [HttpPost("{id:guid}/reset-password")]
    [Authorize(Policy = PolicyConstants.AdminOrSuperAdmin)]
    [ProducesResponseType(typeof(ApiResponse<ResetPasswordResponseDto>), 200)]
    [ProducesResponseType(404)]
    public virtual async Task<IActionResult> ResetPassword(Guid id, [FromBody] ResetPasswordRequestDto request, CancellationToken ct = default)
    {
        if (ValidateGuid(id, "用户ID") is { } error) return error;

        var result = await Sender.Send(new ResetPasswordCommand(id), ct);

        if (!result.IsSuccess)
        {
            if (result.Error == "用户不存在") return NotFound(result.Error);
            return BusinessFail(result.Error ?? "密码重置失败");
        }

        LogOperation("重置用户密码", new { AutoGenerated = true }, id);
        return Success(new ResetPasswordResponseDto
        {
            Success = true,
            TemporaryPassword = result.Value!.TemporaryPassword
        }, "密码重置成功");
    }

    /// <summary>
    /// 修改个人资料
    /// </summary>
    [HttpPut("{id:guid}/profile")]
    [ProducesResponseType(typeof(ApiResponse<UserDetailDto>), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    public virtual async Task<IActionResult> ChangeProfile(Guid id, [FromBody] ChangeProfileDto dto, CancellationToken ct = default)
    {
        var (currentUserId, _, _) = GetOperator();

        var result = await Sender.Send(new ChangeProfileCommand(id, dto, currentUserId), ct);

        if (!result.IsSuccess)
        {
            if (result.Error?.StartsWith("只能修改") == true) return Forbid(result.Error);
            if (result.Error == "用户不存在") return NotFound(result.Error);
            return BusinessFail(result.Error ?? "个人资料修改失败");
        }

        LogOperation("修改个人资料", new { RealName = dto.RealName, PhoneNumber = dto.PhoneNumber }, id);
        return Success(result.Value!, "个人资料修改成功");
    }

    /// <summary>
    /// 修改密码
    /// </summary>
    [HttpPut("{id:guid}/change-password")]
    [ProducesResponseType(typeof(ApiResponse), 200)]
    [ProducesResponseType(400)]
    [ProducesResponseType(404)]
    public virtual async Task<IActionResult> ChangePassword(Guid id, [FromBody] LYBT.Shared.Models.Contracts.Auth.ChangePasswordRequest request, CancellationToken ct = default)
    {
        var (currentUserId, _, _) = GetOperator();

        var result = await Sender.Send(new ChangePasswordCommand(id, request.OldPassword, request.NewPassword, currentUserId), ct);

        if (!result.IsSuccess)
        {
            if (result.Error?.StartsWith("只能修改") == true) return Forbid(result.Error);
            if (result.Error == "用户不存在") return NotFound(result.Error);
            return BusinessFail(result.Error ?? "密码修改失败");
        }

        LogOperation("修改密码", new { UserId = id }, id);
        return Success("密码修改成功");
    }

    /// <summary>
    /// 批量启用用户
    /// </summary>
    [HttpPost("batch-enable")]
    [EnableRateLimiting("ApiCalls")]
    [Authorize(Policy = PolicyConstants.AdminOrSuperAdmin)]
    [ProducesResponseType(typeof(ApiResponse<BatchOperationResultDto>), 200)]
    [ProducesResponseType(typeof(ApiResponse), 400)]
    public virtual async Task<IActionResult> BatchEnable([FromBody] BatchDeleteInputDto dto, CancellationToken ct = default)
    {
        if (dto.Ids == null || dto.Ids.Count == 0)
        {
            return ValidationFail("请至少选择一个用户");
        }

        var result = await Sender.Send(new BatchEnableUsersCommand(dto.Ids), ct);

        LogOperation("批量启用用户", new { Ids = dto.Ids, Result = result.Value?.Message }, null);
        return Success(result.Value!, result.Value?.Message ?? "批量启用完成");
    }

    /// <summary>
    /// 批量禁用用户
    /// </summary>
    [HttpPost("batch-disable")]
    [EnableRateLimiting("ApiCalls")]
    [Authorize(Policy = PolicyConstants.AdminOrSuperAdmin)]
    [ProducesResponseType(typeof(ApiResponse<BatchOperationResultDto>), 200)]
    [ProducesResponseType(typeof(ApiResponse), 400)]
    public virtual async Task<IActionResult> BatchDisable([FromBody] BatchDeleteInputDto dto, CancellationToken ct = default)
    {
        if (dto.Ids == null || dto.Ids.Count == 0)
        {
            return ValidationFail("请至少选择一个用户");
        }

        var result = await Sender.Send(new BatchDisableUsersCommand(dto.Ids), ct);

        LogOperation("批量禁用用户", new { Ids = dto.Ids, Result = result.Value?.Message }, null);
        return Success(result.Value!, result.Value?.Message ?? "批量禁用完成");
    }

    #endregion
}
