<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8625</NoWarn>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions"  />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory"  />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions"  />
    <PackageReference Include="Bogus"  />
    <PackageReference Include="AutoMapper"  />
    <PackageReference Include="Moq"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Server\Core\LYBT.Infrastructure\LYBT.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Server\Core\LYBT.Entities\LYBT.Entities.csproj" />
    <ProjectReference Include="..\..\..\..\src\Server\Modules\LYBT.Module.Herbs\LYBT.Module.Herbs.csproj" />
    <ProjectReference Include="..\..\..\..\src\Shared\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
  </ItemGroup>

</Project>