<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LYBT.WPF.Client.Core\LYBT.WPF.Client.Core.csproj" />
    <ProjectReference Include="..\..\LYBT.WPF.Client.Services\LYBT.WPF.Client.Services.csproj" />
    <ProjectReference Include="..\..\LYBT.WPF.Client.Infrastructure\LYBT.WPF.Client.Infrastructure.csproj" />
  </ItemGroup>

</Project>