<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>LYBT.WPF.Client.Modules.Formula</RootNamespace>
    <AssemblyName>LYBT.WPF.Client.Modules.Formula</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\LYBT.WPF.Client.Core.csproj" />
    <ProjectReference Include="..\..\Services\LYBT.WPF.Client.Services.csproj" />
    <ProjectReference Include="..\..\Infrastructure\LYBT.WPF.Client.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\..\Shared\LYBT.Shared.csproj" />
  </ItemGroup>

</Project>