<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>LYBT.Desktop.Workbench.Admin</AssemblyName>
		<RootNamespace>LYBT.Desktop.Workbench.Admin</RootNamespace>
	    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.DryIoc"  />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\LYBT.Desktop.Workbench.Core.csproj" />
		<ProjectReference Include="..\..\Core\LYBT.Desktop.Core.csproj" />
		<ProjectReference Include="..\..\Services\LYBT.Desktop.Services.csproj" />
		<ProjectReference Include="..\..\..\..\Shared\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
		<ProjectReference Include="..\..\..\..\Shared\LYBT.Shared.Interfaces\LYBT.Shared.Interfaces.csproj" />
	</ItemGroup>

</Project>