using AutoMapper;
using FluentAssertions;
using LYBT.Entities.Users;
using LYBT.Module.Users.Mapping;
using LYBT.Shared.Models.Contracts.Users;
using LYBT.Shared.Models.Enums;
using Xunit;

namespace LYBT.Module.Users.Tests.Mapping
{
    /// <summary>
    /// UserMappingProfile 映射配置测试
    /// 验证用户实体与DTO之间的映射正确性
    /// </summary>
    public class UserMappingProfileTests
    {
        private readonly IMapper _mapper;

        public UserMappingProfileTests()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<UserMappingProfile>();
            });

            _mapper = config.CreateMapper();
        }

        #region 配置有效性测试

        [Fact]
        public void MappingConfiguration_ShouldBeValid()
        {
            // Arrange & Act
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<UserMappingProfile>();
            });

            // Assert
            config.AssertConfigurationIsValid();
        }

        #endregion

        #region User -> UserDto 映射测试

        [Fact]
        public void User_To_UserDto_ShouldMapCorrectly()
        {
            // Arrange
            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = "zhangsan",
                RealName = "张三",
                Email = "zhangsan@test.com",
                PhoneNumber = "13800138000",
                Role = UserRole.Doctor,
                Status = CommonStatus.Enabled,
                PinYinCode = "ZS",
                LastLoginTime = DateTime.Now.AddDays(-1),
                FailedLoginCount = 0,
                CreatedAt = DateTime.Now.AddMonths(-6)
            };

            // Act
            var dto = _mapper.Map<UserDto>(user);

            // Assert
            dto.Should().NotBeNull();
            dto.Id.Should().Be(user.Id);
            dto.UserName.Should().Be(user.UserName);
            dto.RealName.Should().Be(user.RealName);
            dto.Email.Should().Be(user.Email);
            dto.PhoneNumber.Should().Be(user.PhoneNumber);
            dto.Role.Should().Be(user.Role);
            dto.Status.Should().Be(user.Status);
            dto.PinYinCode.Should().Be(user.PinYinCode);
            dto.LastLoginTime.Should().Be(user.LastLoginTime);
            dto.FailedLoginCount.Should().Be(user.FailedLoginCount);
        }

        [Fact]
        public void User_To_UserDto_WithNullOptionalFields_ShouldMapCorrectly()
        {
            // Arrange
            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = "testuser",
                RealName = "测试用户",
                Email = null,
                PhoneNumber = null,
                Role = UserRole.Admin,
                Status = CommonStatus.Enabled,
                PinYinCode = null
            };

            // Act
            var dto = _mapper.Map<UserDto>(user);

            // Assert
            dto.Should().NotBeNull();
            dto.UserName.Should().Be(user.UserName);
            dto.Email.Should().BeNull();
            dto.PhoneNumber.Should().BeNull();
            dto.PinYinCode.Should().BeNull();
        }

        #endregion

        #region UserInputDto -> User 映射测试

        [Fact]
        public void UserCreateDto_To_User_ShouldMapCorrectly()
        {
            // Arrange
            var createDto = new UserInputDto
            {
                UserName = "newuser",
                RealName = "新用户",
                Email = "newuser@test.com",
                PhoneNumber = "13900139000",
                Password = "Password123!",
                ConfirmPassword = "Password123!",
                Role = UserRole.Doctor
            };

            // Act
            var user = _mapper.Map<User>(createDto);

            // Assert
            user.Should().NotBeNull();
            user.UserName.Should().Be(createDto.UserName); // Username映射到UserName
            user.RealName.Should().Be(createDto.RealName);
            user.Email.Should().Be(createDto.Email);
            user.PhoneNumber.Should().Be(createDto.PhoneNumber);
            user.Role.Should().Be(createDto.Role);
        }

        [Fact]
        public void UserCreateDto_To_User_ShouldIgnorePasswordHash()
        {
            // Arrange
            var createDto = new UserInputDto
            {
                UserName = "testuser",
                RealName = "测试",
                Password = "PlainPassword123!",
                ConfirmPassword = "PlainPassword123!"
            };

            // Act
            var user = _mapper.Map<User>(createDto);

            // Assert - PasswordHash应该被忽略（由业务逻辑处理）
            user.PasswordHash.Should().BeEmpty();
        }

        [Fact]
        public void UserCreateDto_To_User_ShouldIgnoreAutoGeneratedFields()
        {
            // Arrange
            var createDto = new UserInputDto
            {
                UserName = "autotest",
                RealName = "自动测试",
                Password = "Pass123!",
                ConfirmPassword = "Pass123!"
            };

            // Act
            var user = _mapper.Map<User>(createDto);

            // Assert - 自动字段应该被忽略
            user.FailedLoginCount.Should().Be(0);
            user.LockoutEnd.Should().BeNull();
            user.PinYinCode.Should().BeNull(); // 由业务逻辑生成
            user.LastLoginTime.Should().BeNull();
            user.Remark.Should().BeNull();
        }

        #endregion

        #region UserInputDto -> User 映射测试

        [Fact]
        public void UserUpdateDto_To_User_ShouldMapAllowedFields()
        {
            // Arrange
            var updateDto = new UserInputDto
            {
                Id = Guid.NewGuid(),
                RealName = "更新的姓名",
                Email = "updated@test.com",
                PhoneNumber = "13700137000",
                Role = UserRole.Doctor
            };

            // Act
            var user = _mapper.Map<User>(updateDto);

            // Assert
            user.Should().NotBeNull();
            user.RealName.Should().Be(updateDto.RealName);
            user.Email.Should().Be(updateDto.Email);
            user.PhoneNumber.Should().Be(updateDto.PhoneNumber);
            user.Role.Should().Be(updateDto.Role.Value);
        }

        [Fact]
        public void UserUpdateDto_To_User_ShouldIgnoreUserName()
        {
            // Arrange
            var updateDto = new UserInputDto
            {
                Id = Guid.NewGuid(),
                RealName = "测试更新"
                // UserName不在UpdateDto中，应该被忽略
            };

            // Act
            var user = _mapper.Map<User>(updateDto);

            // Assert - UserName应该为空（未映射）
            user.UserName.Should().BeEmpty();
        }

        [Fact]
        public void UserUpdateDto_To_User_ShouldIgnorePasswordAndSecurityFields()
        {
            // Arrange
            var updateDto = new UserInputDto
            {
                Id = Guid.NewGuid(),
                RealName = "安全测试"
            };

            // Act
            var user = _mapper.Map<User>(updateDto);

            // Assert - 安全字段应该被忽略
            user.PasswordHash.Should().BeEmpty();
            user.FailedLoginCount.Should().Be(0);
            user.LockoutEnd.Should().BeNull();
            user.LastLoginTime.Should().BeNull();
        }

        #endregion

        #region 角色与状态映射测试

        [Theory]
        [InlineData(UserRole.Admin)]
        [InlineData(UserRole.Doctor)]
        public void User_To_UserDto_ShouldMapAllRoles(UserRole role)
        {
            // Arrange
            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = "roletest",
                RealName = "角色测试",
                Role = role,
                Status = CommonStatus.Enabled
            };

            // Act
            var dto = _mapper.Map<UserDto>(user);

            // Assert
            dto.Role.Should().Be(role);
        }

        [Theory]
        [InlineData(CommonStatus.Enabled)]
        [InlineData(CommonStatus.Disabled)]
        public void User_To_UserDto_ShouldMapAllStatuses(CommonStatus status)
        {
            // Arrange
            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = "statustest",
                RealName = "状态测试",
                Role = UserRole.Doctor,
                Status = status
            };

            // Act
            var dto = _mapper.Map<UserDto>(user);

            // Assert
            dto.Status.Should().Be(status);
        }

        #endregion

        #region 边界条件测试

        [Fact]
        public void Mapping_WithNullSource_ShouldReturnNull()
        {
            // Arrange
            User? nullUser = null;

            // Act
            var dto = _mapper.Map<UserDto>(nullUser);

            // Assert
            dto.Should().BeNull();
        }

        [Fact]
        public void UserCreateDto_WithMinimalData_ShouldMapSuccessfully()
        {
            // Arrange
            var createDto = new UserInputDto
            {
                UserName = "minimal",
                RealName = "最小数据",
                Password = "Pass123!",
                ConfirmPassword = "Pass123!"
                // 其他字段为null
            };

            // Act
            var user = _mapper.Map<User>(createDto);

            // Assert
            user.Should().NotBeNull();
            user.UserName.Should().Be("minimal");
            user.RealName.Should().Be("最小数据");
            user.Email.Should().BeNull();
            user.PhoneNumber.Should().BeNull();
        }

        [Fact]
        public void UserUpdateDto_WithPartialData_ShouldMapOnlyProvidedFields()
        {
            // Arrange
            var updateDto = new UserInputDto
            {
                Id = Guid.NewGuid(),
                RealName = "部分更新",
                Email = "partial@test.com"
                // 其他字段为null
            };

            // Act
            var user = _mapper.Map<User>(updateDto);

            // Assert
            user.Should().NotBeNull();
            user.RealName.Should().Be("部分更新");
            user.Email.Should().Be("partial@test.com");
            user.PhoneNumber.Should().BeNull();
        }

        #endregion

        #region 特殊字符测试

        [Fact]
        public void User_To_UserDto_WithSpecialCharactersInName_ShouldMapCorrectly()
        {
            // Arrange
            var user = new User
            {
                Id = Guid.NewGuid(),
                UserName = "special_user",
                RealName = "欧阳·修",
                Email = "test+tag@example.com",
                Role = UserRole.Doctor,
                Status = CommonStatus.Enabled,
                PinYinCode = "OYX"
            };

            // Act
            var dto = _mapper.Map<UserDto>(user);

            // Assert
            dto.RealName.Should().Be("欧阳·修");
            dto.Email.Should().Be("test+tag@example.com");
            dto.PinYinCode.Should().Be("OYX");
        }

        #endregion
    }
}
