// <auto-generated/>
// JSON Source Generation Context for LYBT WebAPI
// Issue 4.2: Enable System.Text.Json source code generators
//
// This context provides compile-time JSON serialization metadata,
// eliminating runtime reflection overhead and enabling AOT/Trimming compatibility.

using System.Text.Json.Serialization;
using LYBT.Shared.Models.Contracts.Auth;
using LYBT.Shared.Models.Contracts.Common;
using LYBT.Shared.Models.Contracts.Consultation;
using LYBT.Shared.Models.Contracts.Formula;
using LYBT.Shared.Models.Contracts.Herbs;
using LYBT.Shared.Models.Contracts.MedicalCase;
using LYBT.Shared.Models.Contracts.Patients;
using LYBT.Shared.Models.Contracts.Prescriptions;
using LYBT.Shared.Models.Contracts.Users;

namespace LYBT.WebAPI.Serialization;

// ============================================================
// Common Types
// ============================================================

[JsonSerializable(typeof(ApiResponse))]
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<bool>))]
[JsonSerializable(typeof(ApiResponse<int>))]
[JsonSerializable(typeof(ApiResponse<Guid>))]
[JsonSerializable(typeof(HealthCheckResponse))]
[JsonSerializable(typeof(HealthStatusDto))]
[JsonSerializable(typeof(OperationResultDto))]
[JsonSerializable(typeof(PagedQueryBaseDto))]

// ============================================================
// Auth Types
// ============================================================

[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(RefreshTokenRequest))]
[JsonSerializable(typeof(LogoutRequest))]
[JsonSerializable(typeof(AutoLoginRequest))]
[JsonSerializable(typeof(SuperAdminLoginRequest))]
[JsonSerializable(typeof(ValidateTokenRequest))]
[JsonSerializable(typeof(ValidateTokenResponse))]
[JsonSerializable(typeof(ChangeSysAdminPassword))]

// ============================================================
// Users Types
// ============================================================

[JsonSerializable(typeof(UserDetailDto))]
[JsonSerializable(typeof(UserListDto))]
[JsonSerializable(typeof(UserInputDto))]
[JsonSerializable(typeof(ChangePasswordDto))]
[JsonSerializable(typeof(ChangeProfileDto))]
[JsonSerializable(typeof(ResetPasswordRequestDto))]
[JsonSerializable(typeof(ResetPasswordResponseDto))]

// ============================================================
// Patients Types
// ============================================================

[JsonSerializable(typeof(PatientDetailDto))]
[JsonSerializable(typeof(PatientListDto))]
[JsonSerializable(typeof(PatientInputDto))]
[JsonSerializable(typeof(PatientBasicDto))]

// ============================================================
// Herbs Types
// ============================================================

[JsonSerializable(typeof(HerbDetailDto))]
[JsonSerializable(typeof(HerbListDto))]
[JsonSerializable(typeof(HerbInputDto))]
[JsonSerializable(typeof(HerbBasicDto))]
[JsonSerializable(typeof(HerbReferenceCheckDto))]

// ============================================================
// Formula Types
// ============================================================

[JsonSerializable(typeof(FormulaDetailDto))]
[JsonSerializable(typeof(FormulaListDto))]
[JsonSerializable(typeof(FormulaInputDto))]
[JsonSerializable(typeof(FormulaHerbItemDto))]
[JsonSerializable(typeof(FormulaHerbItemInputDto))]
[JsonSerializable(typeof(FormulaImportItemDto))]
[JsonSerializable(typeof(FormulaHerbImportItemDto))]

// ============================================================
// MedicalCase Types
// ============================================================

[JsonSerializable(typeof(MedicalCaseDetailDto))]
[JsonSerializable(typeof(MedicalCaseListDto))]
[JsonSerializable(typeof(MedicalCaseInputDto))]
[JsonSerializable(typeof(MedicalCaseQueryDto))]
[JsonSerializable(typeof(MedicalCaseStatusInputDto))]
[JsonSerializable(typeof(PendingMedicalCaseDto))]
[JsonSerializable(typeof(BatchDetailQueryDto))]
[JsonSerializable(typeof(SetPrescriptionFlagRequest))]

// ============================================================
// Consultation Types
// ============================================================

[JsonSerializable(typeof(ConsultationDetailDto))]
[JsonSerializable(typeof(ConsultationInputDto))]

// ============================================================
// Prescription Types
// ============================================================

[JsonSerializable(typeof(PrescriptionDetailDto))]
[JsonSerializable(typeof(PrescriptionInputDto))]
[JsonSerializable(typeof(PrescriptionItemDto))]
[JsonSerializable(typeof(PrescriptionItemInputDto))]

// ============================================================
// Generic Types (common combinations)
// ============================================================

[JsonSerializable(typeof(ApiResponse<UserDetailDto>))]
[JsonSerializable(typeof(ApiResponse<LoginResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<UserListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<PatientListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<HerbListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<FormulaListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<MedicalCaseListDto>>))]
[JsonSerializable(typeof(ApiResponse<PagedResult<PendingMedicalCaseDto>>))]
[JsonSerializable(typeof(ApiResponse<MedicalCaseDetailDto>))]
[JsonSerializable(typeof(ApiResponse<PatientDetailDto>))]
[JsonSerializable(typeof(ApiResponse<HerbDetailDto>))]
[JsonSerializable(typeof(ApiResponse<FormulaDetailDto>))]
[JsonSerializable(typeof(ApiResponse<HealthCheckResponse>))]
[JsonSerializable(typeof(ApiResponse<HealthStatusDto>))]
[JsonSerializable(typeof(ApiResponse<OperationResultDto>))]

// ============================================================
// Common List Types
// ============================================================

[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<Guid>))]
[JsonSerializable(typeof(List<int>))]

// ============================================================
// Context Definition
// ============================================================

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Serialization | JsonSourceGenerationMode.Metadata,
    IgnoreReadOnlyFields = false,
    IgnoreReadOnlyProperties = false)]
public partial class LybtJsonContext : JsonSerializerContext
{
}


