// <auto-generated />
using System;
using LYBT.Module.DiagnosisTreatment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LYBT.Module.DiagnosisTreatment.Migrations
{
    [DbContext(typeof(DiagnosisTreatmentDbContext))]
    partial class DiagnosisTreatmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LYBT.Module.DiagnosisTreatment.Models.DiagnosisTreatmentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiagnosisCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentIllness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiagnosisTreatments", (string)null);
                });

            modelBuilder.Entity("LYBT.Module.DiagnosisTreatment.Models.DiagnosisTreatmentModel", b =>
                {
                    b.OwnsMany("LYBT.Module.DiagnosisTreatment.Models.TreatmentItemModel", "Treatments", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Count")
                                .HasColumnType("int");

                            b1.Property<Guid>("DiagnosisTreatmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("Id");

                            b1.HasIndex("DiagnosisTreatmentId");

                            b1.ToTable("DiagnosisTreatmentItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DiagnosisTreatmentId");
                        });

                    b.OwnsOne("LYBT.Module.DiagnosisTreatment.Models.FormulaModel", "Formula", b1 =>
                        {
                            b1.Property<Guid>("DiagnosisTreatmentModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("DiagnosisTreatmentModelId");

                            b1.ToTable("DiagnosisTreatments");

                            b1.WithOwner()
                                .HasForeignKey("DiagnosisTreatmentModelId");

                            b1.OwnsMany("LYBT.Module.DiagnosisTreatment.Models.HerbItemModel", "Herbs", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(10,3)");

                                    b2.Property<Guid>("DiagnosisTreatmentId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("HerbId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<decimal>("UnitPrice")
                                        .HasColumnType("decimal(18,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("DiagnosisTreatmentId");

                                    b2.ToTable("DiagnosisTreatmentFormulaHerbs", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("DiagnosisTreatmentId");
                                });

                            b1.Navigation("Herbs");
                        });

                    b.Navigation("Formula");

                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
