<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LYBT.Module.MedicalCases</RootNamespace>
    <AssemblyName>LYBT.Module.MedicalCases</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\LYBT.Infrastructure\LYBT.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Core/LYBT.Entities/LYBT.Entities.csproj" />
    <ProjectReference Include="..\..\..\Shared\LYBT.Shared.Models\LYBT.Shared.Models.csproj" />
    <ProjectReference Include="..\..\..\Shared\LYBT.Shared.Validators\LYBT.Shared.Validators.csproj" />
    <ProjectReference Include="..\LYBT.Module.Patients\LYBT.Module.Patients.csproj" />
    <ProjectReference Include="..\LYBT.Module.Users\LYBT.Module.Users.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- OpenSpec: adopt-mapperly-unified-mapping - 迁移到Mapperly -->
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>