<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\BIN</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LYBT.Module.Herbs\LYBT.Module.Herbs.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\LYBT.Module.FormulaTemplates\LYBT.Module.FormulaTemplates.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
  </ItemGroup>

</Project>
