using AutoMapper;
using FluentAssertions;
using LYBT.Entities.Patients;
using LYBT.Module.Patients.Mapping;
using LYBT.Shared.Models.Contracts.Patients;
using LYBT.Shared.Models.Enums;
using Xunit;

namespace LYBT.Module.Patients.Tests.Mapping
{
    /// <summary>
    /// PatientMappingProfile 映射配置测试
    /// 验证患者实体与DTO之间的映射正确性
    /// </summary>
    public class PatientMappingProfileTests
    {
        private readonly IMapper _mapper;

        public PatientMappingProfileTests()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<PatientMappingProfile>();
            });

            _mapper = config.CreateMapper();
        }

        #region 配置有效性测试

        [Fact]
        public void MappingConfiguration_ShouldBeValid()
        {
            // Arrange & Act
            var config = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<PatientMappingProfile>();
            });

            // Assert
            config.AssertConfigurationIsValid();
        }

        #endregion

        #region Patient -> PatientDto 映射测试

        [Fact]
        public void Patient_To_PatientDto_ShouldMapCorrectly()
        {
            // Arrange
            var patient = new Patient
            {
                Id = Guid.NewGuid(),
                Name = "张三",
                Gender = Gender.Male,
                BirthDate = new DateTime(1980, 5, 15),
                PhoneNumber = "13800138000",
                IdNumber = "110101198005151234",
                Address = "北京市朝阳区某某街道",
                PinYinCode = "ZS",
                Status = CommonStatus.Enabled,
                VisitCount = 5,
                LastVisitTime = DateTime.Now.AddDays(-7),
                EmergencyContactName = "李四",
                EmergencyContactPhone = "13900139000",
                AllergyHistory = "青霉素",
                CreatedAt = DateTime.Now.AddYears(-2)
            };

            // Act
            var dto = _mapper.Map<PatientDto>(patient);

            // Assert
            dto.Should().NotBeNull();
            dto.Id.Should().Be(patient.Id);
            dto.Name.Should().Be(patient.Name);
            dto.Gender.Should().Be(patient.Gender);
            dto.BirthDate.Should().Be(patient.BirthDate);
            dto.PhoneNumber.Should().Be(patient.PhoneNumber);
            dto.IdNumber.Should().Be(patient.IdNumber);
            dto.Address.Should().Be(patient.Address);
            dto.PinYinCode.Should().Be(patient.PinYinCode);
            dto.Status.Should().Be(patient.Status);
            dto.EmergencyContactName.Should().Be(patient.EmergencyContactName);
            dto.EmergencyContactPhone.Should().Be(patient.EmergencyContactPhone);
            dto.AllergyHistory.Should().Be(patient.AllergyHistory);
        }

        [Fact]
        public void Patient_To_PatientDto_ShouldIgnoreAgeProperty()
        {
            // Arrange
            var patient = new Patient
            {
                Id = Guid.NewGuid(),
                Name = "测试患者",
                BirthDate = new DateTime(1990, 1, 1),
                Gender = Gender.Female,
                Status = CommonStatus.Enabled
            };

            // Act
            var dto = _mapper.Map<PatientDto>(patient);

            // Assert - Age 是计算属性，由 DTO 根据 BirthDate 自动计算
            dto.Age.Should().NotBeNull();
            dto.Age.Should().Be(DateTime.Today.Year - 1990); // 基于出生年份计算
        }

        #endregion

        #region PatientInputDto -> Patient 映射测试

        [Fact]
        public void PatientCreateDto_To_Patient_ShouldMapCorrectly()
        {
            // Arrange
            var createDto = new PatientInputDto
            {
                Name = "新患者",
                Gender = Gender.Male,
                BirthDate = new DateTime(1985, 3, 20),
                PhoneNumber = "13700137000",
                IdNumber = "110101198503201234",
                Address = "上海市浦东新区",
                EmergencyContactName = "王五",
                EmergencyContactPhone = "13600136000",
                AllergyHistory = "海鲜"
            };

            // Act
            var patient = _mapper.Map<Patient>(createDto);

            // Assert
            patient.Should().NotBeNull();
            patient.Name.Should().Be(createDto.Name);
            patient.Gender.Should().Be(createDto.Gender);
            patient.BirthDate.Should().Be(createDto.BirthDate);
            patient.PhoneNumber.Should().Be(createDto.PhoneNumber);
            patient.IdNumber.Should().Be(createDto.IdNumber);
            patient.Address.Should().Be(createDto.Address);
            patient.EmergencyContactName.Should().Be(createDto.EmergencyContactName);
            patient.EmergencyContactPhone.Should().Be(createDto.EmergencyContactPhone);
            patient.AllergyHistory.Should().Be(createDto.AllergyHistory);
        }

        [Fact]
        public void PatientCreateDto_To_Patient_ShouldIgnoreAutoGeneratedFields()
        {
            // Arrange
            var createDto = new PatientInputDto
            {
                Name = "自动字段测试",
                Gender = Gender.Female,
                BirthDate = new DateTime(1995, 6, 10)
            };

            // Act
            var patient = _mapper.Map<Patient>(createDto);

            // Assert - 自动生成字段应该被忽略
            patient.Age.Should().Be(DateTime.Today.Year - 1995); // Age 是计算属性，由实体根据 BirthDate 计算
            patient.PinYinCode.Should().BeNull(); // 由业务逻辑生成
            patient.LastVisitTime.Should().BeNull();
            patient.VisitCount.Should().Be(0);
            patient.DisableReason.Should().BeNull();
            patient.Status.Should().Be(CommonStatus.Enabled); // Patient 实体默认值是 Enabled
        }

        #endregion

        #region PatientInputDto -> Patient 映射测试

        [Fact]
        public void PatientUpdateDto_To_Patient_ShouldMapAllowedFields()
        {
            // Arrange
            var updateDto = new PatientInputDto
            {
                Name = "更新的姓名",
                PhoneNumber = "13500135000",
                Address = "广州市天河区",
                EmergencyContactName = "赵六",
                EmergencyContactPhone = "13400134000",
                AllergyHistory = "花粉"
            };

            // Act
            var patient = _mapper.Map<Patient>(updateDto);

            // Assert
            patient.Should().NotBeNull();
            patient.Name.Should().Be(updateDto.Name);
            patient.PhoneNumber.Should().Be(updateDto.PhoneNumber);
            patient.Address.Should().Be(updateDto.Address);
            patient.EmergencyContactName.Should().Be(updateDto.EmergencyContactName);
            patient.EmergencyContactPhone.Should().Be(updateDto.EmergencyContactPhone);
            patient.AllergyHistory.Should().Be(updateDto.AllergyHistory);
        }

        [Fact]
        public void PatientUpdateDto_To_Patient_ShouldOnlyMapNonNullValues()
        {
            // Arrange
            var updateDto = new PatientInputDto
            {
                Name = "部分更新",
                PhoneNumber = null, // null值应该被跳过
                Address = null
            };

            // Act
            var patient = _mapper.Map<Patient>(updateDto);

            // Assert - ForAllMembers条件会跳过null值
            patient.Name.Should().Be("部分更新");
            patient.PhoneNumber.Should().BeNull();
            patient.Address.Should().BeNull();
        }

        #endregion

        #region PatientDto -> Patient 映射测试

        [Fact]
        public void PatientDto_To_Patient_ShouldMapCorrectly()
        {
            // Arrange
            var patientDto = new PatientDto
            {
                Id = Guid.NewGuid(),
                Name = "DTO患者",
                Gender = Gender.Male,
                BirthDate = new DateTime(1978, 12, 5),
                PhoneNumber = "13300133000",
                IdNumber = "110101197812051234",
                PinYinCode = "DTOHZ",
                Status = CommonStatus.Enabled
            };

            // Act
            var patient = _mapper.Map<Patient>(patientDto);

            // Assert
            patient.Should().NotBeNull();
            patient.Id.Should().Be(patientDto.Id);
            patient.Name.Should().Be(patientDto.Name);
            patient.Gender.Should().Be(patientDto.Gender);
            patient.BirthDate.Should().Be(patientDto.BirthDate);
            patient.PhoneNumber.Should().Be(patientDto.PhoneNumber);
            patient.IdNumber.Should().Be(patientDto.IdNumber);
            patient.PinYinCode.Should().Be(patientDto.PinYinCode);
        }

        #endregion

        #region PatientInputDto -> PatientDto 映射测试

        [Fact]
        public void PatientCreateDto_To_PatientDto_ShouldMapCorrectly()
        {
            // Arrange
            var createDto = new PatientInputDto
            {
                Name = "创建DTO",
                Gender = Gender.Female,
                BirthDate = new DateTime(1992, 8, 25),
                PhoneNumber = "13200132000"
            };

            // Act
            var patientDto = _mapper.Map<PatientDto>(createDto);

            // Assert
            patientDto.Should().NotBeNull();
            patientDto.Name.Should().Be(createDto.Name);
            patientDto.Gender.Should().Be(createDto.Gender);
            patientDto.BirthDate.Should().Be(createDto.BirthDate);
            patientDto.PhoneNumber.Should().Be(createDto.PhoneNumber);
        }

        [Fact]
        public void PatientCreateDto_To_PatientDto_ShouldIgnoreSystemFields()
        {
            // Arrange
            var createDto = new PatientInputDto
            {
                Name = "系统字段测试",
                Gender = Gender.Male,
                BirthDate = new DateTime(1988, 4, 15)
            };

            // Act
            var patientDto = _mapper.Map<PatientDto>(createDto);

            // Assert
            patientDto.PinYinCode.Should().BeNull(); // 系统生成
            patientDto.LastVisitTime.Should().BeNull();
            patientDto.VisitCount.Should().Be(0);
            patientDto.DisableReason.Should().BeNull();
        }

        #endregion

        #region PatientInputDto -> PatientDto 映射测试

        [Fact]
        public void PatientUpdateDto_To_PatientDto_ShouldMapCorrectly()
        {
            // Arrange
            var updateDto = new PatientInputDto
            {
                Name = "更新DTO",
                PhoneNumber = "13100131000",
                Address = "深圳市南山区"
            };

            // Act
            var patientDto = _mapper.Map<PatientDto>(updateDto);

            // Assert
            patientDto.Should().NotBeNull();
            patientDto.Name.Should().Be(updateDto.Name);
            patientDto.PhoneNumber.Should().Be(updateDto.PhoneNumber);
            patientDto.Address.Should().Be(updateDto.Address);
        }

        #endregion

        #region 性别映射测试

        [Theory]
        [InlineData(Gender.Male)]
        [InlineData(Gender.Female)]
        [InlineData(Gender.Unknown)]
        public void Patient_To_PatientDto_ShouldMapAllGenders(Gender gender)
        {
            // Arrange
            var patient = new Patient
            {
                Id = Guid.NewGuid(),
                Name = "性别测试",
                Gender = gender,
                BirthDate = new DateTime(1990, 1, 1),
                Status = CommonStatus.Enabled
            };

            // Act
            var dto = _mapper.Map<PatientDto>(patient);

            // Assert
            dto.Gender.Should().Be(gender);
        }

        #endregion

        #region 边界条件测试

        [Fact]
        public void Mapping_WithNullSource_ShouldReturnNull()
        {
            // Arrange
            Patient? nullPatient = null;

            // Act
            var dto = _mapper.Map<PatientDto>(nullPatient);

            // Assert
            dto.Should().BeNull();
        }

        [Fact]
        public void PatientCreateDto_WithMinimalData_ShouldMapSuccessfully()
        {
            // Arrange
            var createDto = new PatientInputDto
            {
                Name = "最小数据",
                Gender = Gender.Male,
                BirthDate = new DateTime(2000, 1, 1)
                // 其他字段为null
            };

            // Act
            var patient = _mapper.Map<Patient>(createDto);

            // Assert
            patient.Should().NotBeNull();
            patient.Name.Should().Be("最小数据");
            patient.PhoneNumber.Should().BeNull();
            patient.Address.Should().BeNull();
        }

        [Fact]
        public void Patient_WithNullOptionalFields_ShouldMapCorrectly()
        {
            // Arrange
            var patient = new Patient
            {
                Id = Guid.NewGuid(),
                Name = "可选字段测试",
                Gender = Gender.Female,
                BirthDate = new DateTime(1985, 6, 10),
                Status = CommonStatus.Enabled,
                PhoneNumber = null,
                IdNumber = null,
                Address = null,
                EmergencyContactName = null,
                EmergencyContactPhone = null,
                AllergyHistory = null
            };

            // Act
            var dto = _mapper.Map<PatientDto>(patient);

            // Assert
            dto.Should().NotBeNull();
            dto.Name.Should().Be("可选字段测试");
            dto.PhoneNumber.Should().BeNull();
            dto.Address.Should().BeNull();
        }

        #endregion

        #region 特殊字符测试

        [Fact]
        public void Patient_WithSpecialCharacters_ShouldMapCorrectly()
        {
            // Arrange
            var patient = new Patient
            {
                Id = Guid.NewGuid(),
                Name = "欧阳·修",
                Gender = Gender.Male,
                BirthDate = new DateTime(1975, 10, 20),
                Status = CommonStatus.Enabled,
                Address = "北京市/朝阳区/某某街道（1号楼）",
                AllergyHistory = "青霉素、链霉素"
            };

            // Act
            var dto = _mapper.Map<PatientDto>(patient);

            // Assert
            dto.Name.Should().Be("欧阳·修");
            dto.Address.Should().Be("北京市/朝阳区/某某街道（1号楼）");
            dto.AllergyHistory.Should().Be("青霉素、链霉素");
        }

        #endregion
    }
}
